### PR TITLE
Use polyfill without depending on global scope

### PR DESCRIPTION
**Pull request by julka**
I'm trying to use this in an environment where I don't have control over what's happening in the global scope of the page, and I'd rather not populate an Intl polyfill outside my own scope. 

Would you consider a change like this that allow me to pass in the desired Intl object when needed?

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
Couldn't you have a closure where you make an `Intl` binding available, and have this package inside that closure so it can see your `Intl`? This would be shadowing the global scope's `Intl`, but seems like what you'd want in this use case.

**Comment by julka** [comment]
I'd like to to use this in a project built with Webpack. While I'm very open to changing how I'm going about this, neither moving away from Webpack nor putting things in global scope are an option on this project.

This is an oversimplification, but here's an idea of what's happening in what scopes when using Webkit:

```
function() {
    var require = function(file) {
        var files = {};

        files['foo'] = function() {
            return module.exports from file;
        };

        files['bar'] = function() {
            return module.exports from file;
        };

        return files[file];
    };

    // let's do real stuff now
    function() {
        var intlPollyfill = require('foo');

        // this doesn't have direct access to what's being done in this
        // function, or what was done in foo
        var intlMessageformat = require('bar');
    }();
}();
```

**Comment by jasonmit** [comment]
I don't believe this is necessary, closing for now.

**Pull request closed without merging**
