### PR TITLE
fix #154 values for 0

### LINKED ISSUE #154: values for 0
var IntlMessageFormat = require('intl-messageformat');
var msg = new IntlMessageFormat('number is {n}.', 'en-US');
msg.format({n:0}); 
// expect "number is 0." 
// but got "number is ."

### PR DESCRIPTION
**Pull request by cwtuan**

### CODE REVIEW

**Comment by cwtuan** [comment]
@ericf  Could you please merge it and publish?

**Comment by scriby** [comment]
Also fixes #88, #112, #119, #127, #136, #141, #144, and an untold number of future issues caused by developers making a perfectly reasonable assumption about the behavior of this library.

**Comment by jasonmit** [comment]
@caridy any chance we can land this?

**Comment by cwtuan** [comment]
could anyone accept the PR?

**Comment by jasonmit** [comment]
@cwtuan not that I'm aware of.  Many of us have left Yahoo and it doesn't seem this project is maintained.  I'm willing to take ownership or hard fork.

**Comment by cwtuan** [comment]
@jasonmit Could I take the ownership too? I'm willing to maintain this project

**Comment by steida** [comment]
@ericf How we can help you with PR?

**Comment by okuryu** [comment]
Could you add tests for this?

**Comment by steida** [comment]
@okuryu Doing OSS 24/7 already :-/

**Comment by rlivsey** [comment]
@cwtuan feel free to pull in the tests I wrote for https://github.com/yahoo/intl-messageformat/pull/112

**Comment by MaKleSoft** [comment]
How is this not merged after over two months? It's a straightforward fix for a very prominent problem! Can somebody please just hit that merge button?

**Comment by steida** [comment]
I always wonder what terrible had to happen in maintainers life that they even don't bother to answer or kill the project with some short explanation. And yet, I am open source maintainer too.

**Comment by steida** [comment]
I see, caridy@gmail.com doesn't work for Yahoo anymore.

**Comment by steida** [comment]
Ok, let's fork it.

**Comment by steida** [comment]
I was chatting with former Yahoo developers, it seems nobody in Yahoo is interested in maintenance. We have to fork it probably.

**Comment by okuryu** [comment]
Last month I got commit bits of all repositories of FormatJS suite including intl-messageformat, so I will cooperate with maintenance. I definitely would like to cooperate with these maintenance.

**Comment by MaKleSoft** [comment]
Does this mean https://formatjs.io/ is dead?

**Comment by steida** [comment]
Probably is. It has all symptoms. Key people left the company, and the company doesn't care about open source at all.

**Comment by jasonmit** [comment]
@okuryu do have npm access?

If not - I'm happy to fork and manage it as part of ember-intl (still maintained)

**Pull request merged**
