### PR TITLE
Add `selectordinal` support and improve locale data

### LINKED ISSUE #84: How about ordinals?
It would be great if intl-messageformat supported ordinal numbers:

1st, 2nd, 3rd, 4th, 10th, 11th, 12th, 13th, 52nd, 53rd, etc...

Here is a really simple version of the logic:

```
    function ordinal_suffix(num) {
        var s = ["th", "st", "nd", "rd"],
            v = num % 100;
        return num + (s[(v - 20) % 10] || s[v] || s[0]);
    }
```

I am unsure if ordinal works differently in other languages besides english

### PR DESCRIPTION
**Pull request by ericf**
This upgrades to `intl-messageformat-parser@1.1.0` and adds support for `selectordinal` arguments; e.g.:

```
This is my {year, selectordinal,
    one {#st}
    two {#nd}
    few {#rd}
    other{#th}
} birthday.
```

The locale data has also been vastly improved in the following ways:

* Added `pt-PT` plural rule function, which differs from `pt`'s.

* Properly de-duplicate data for all CLDR locales by correctly traversing a locale's hierarchy of ancestor locales.

* Added data for the following languages:
  aa, agq, bas, bh, ckb, dav, dje, dsb, dua, dv, dyo, ebu, ewo, guw, guz, hsb, ia, in, iu, iw, jbo, ji, jv, jw, kaj, kam, kcg, khq, ki, kln, kok, ksf, ku, lb, lu, luo, luy, mer, mfe, mgh, mo, mua, nah, nmg, no, nqo, nus, ny, pap, prg, qu, rn, rw, sbp, sh, sma, smi, smj, smn, sms, swc, syr, tk, tl, twq, vai, wa, wo, yav, yi, zgh

----

These changes also include improvements for how locales are resolved. Here are some details of these changes:

* If no extra locale data is loaded, the locale will _always_ resolved to `en`.

* If locale data is missing for a leaf locale like `fr-FR`, but there _is_ data for the root, `fr` in this case, then its root will be used.

* If there's data for the specified locale, then that locale will be resolved; i.e.,

  ```js
  var mf = new IntlMessageFormat('', 'en-US');
  assert(mf.resolvedOptions().locale === 'en-US'); // true
  ```

* The resolved locales are now normalized; e.g., `en-us` will resolve to: `en-US`.

Fixes #84

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
**Note:** This PR does not include the `dist/` changes since that would make it unmanageable to review.

**Comment by caridy** [comment]
:rocket:

**Comment by ericf** [comment]
@jasonmit Did you want to review this?

**Comment by jasonmit** [comment]
LGTM :+1:

**Comment by ericf** [comment]
The new plural rule functions generated via make-plural use `substr()` with negative values which is not supported in IE < 9. We'll need an updated `make-plural` before publishing these changes to npm.

https://github.com/eemeli/make-plural.js/issues/5

**Comment by eemeli** [comment]
I fixed make-plural to use `slice()` instead of `substr()`, which ought to make it work in older IEs, and published this in npm as `make-plural@2.1.3`.

As a heads-up, I'm working on migrating the make-plural codebase to ES6, and will be eventually publishing that as v2.2 or v3. The idea is to use Babel to transpile it to ES5, and still publish a version using `require()` in npm.

**Comment by ericf** [comment]
@eemeli thanks for pushing out the fix! I tested it and everything is working as expected.

Re: ES6 sounds good. We're only using make-plural as a dev dependency, but all of our [FormatJS](http://formatjs.io/) libs are written as ES6 modules transpiled to ES5/3 — although we haven't yet switched to using Babel.

**Pull request merged**
