### PR TITLE
Add missing sourcemap files

### PR DESCRIPTION
**Pull request by pawsong**
Add missing sourcemap files in lib directory.

### CODE REVIEW

**Comment by christophehurpeau** [comment]
Any update on this ?

**Comment by peterjuras** [comment]
Can this please be merged?

**Comment by schabluk** [comment]
Merge please.

**Comment by pawsong** [comment]
@ericf Hi! Is there any issue that prevents from being merged?

**Comment by wazzzap** [comment]
Any updates on this?

**Comment by jasonmit** [comment]
This will be in the next release.  Thanks.

**Pull request merged**
