### PR TITLE
Bump version to v2.0.0

### PR DESCRIPTION
**Pull request by okuryu**

### CODE REVIEW

**Comment by jasonmit** [comment]
@okuryu might be worth bumping major since it's technically changing the behavior that people may be relying on.  Also - thank you for helping get this through :)

**Comment by okuryu** [comment]
Okay, I changed to v2.0.0.

**Comment by jasonmit** [comment]
@okuryu I opened a PR against intl-relativeformat to start pulling in this dep change

**Comment by catamphetamine** [comment]
So, what has actually changed???
And how to upgrade?

**Pull request merged**
